### ISSUE TITLE
Unit tests not working

### ISSUE THREAD

**Issue by boboldehampsink** [zendframework/ZendService_Apple_Apns#33]
There's nothing connected to travis, and the unit tests won't run

**Comment by samsonasik** [comment]
linked with #34

**Comment by mwillbanks** [comment]
@boboldehampsink i may merge this in for now; however, I am going to be updating the library to support PSR-4 for autoloading as well as updating the way that the build runs.

**Comment by Breuls** [comment]
I almost started on fixing the Travis builds until I discovered this issue (and PR #34) being open for two months. Are there any plans to still maintain this repository?

**Comment by mwillbanks** [comment]
@Breuls it is still maintained; the unit tests themselves does not make it for a releasable point release.  Moving to PSR-4 will which is on my list but I am currently bogged down with other items at this time.  I should be able to get to it this week however.

**Comment by Breuls** [comment]
Awesome. I was originally looking into the tests because I wanted to see if #38 broke by itself (Travis currently fails on it) or because of something else. But the affected code apparently is not covered by tests at all.

That PR solves a bug I'm running into, by the way. I'm currently overriding a method to fix it outside of the  Zend code, but it would be nice if I could remove it and use it straight from here again.

**Comment by mwillbanks** [comment]
Fixed with #34
